global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'urbackup'
    static_configs:
      - targets: ['urbackup-exporter:9554']
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']