{
 "title": "UrBackup Exporter",
 "description": "UrBackup dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Last backup",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_lasttime{backup_type=\"file\"} * 1000",
     "legendFormat": "{{client_name}}"
    },
    {
     "expr": "time() - urbackup_backup_lasttime{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Last backup status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_ok{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "urbackup_client_online", "legendFormat": "{{client_name}}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_size_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup count",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_number_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client details",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urbackup_backup_lasttime{backup_type=\"file\"}",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/vda2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens3\"}[1m]) / 1024 / 1024 * 10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client status (online)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(client_name)(urbackup_client_online)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_size_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total backup count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_name)(urbackup_backup_number_total)",
     "legendFormat": "{{client_name}}"
    }
   ]
  }
 ]
}